Repository parrt/dtreeviz, pull requests merged in 2022-12, with the labels that each got.

#205 start reorg of readme
  README.md
  testing/samples/titanic-leaf-regression.png
  testing/samples/titanic-leaf-samples-by-class.png
Labels: doc

#210 Small cleanup of API
  dtreeviz/classifiers.py
  dtreeviz/trees.py
Labels: clean up

#214 More cleanup
  dtreeviz/__init__.py
  dtreeviz/classifiers.py
  dtreeviz/compatibility.py
  dtreeviz/interpretation.py
  dtreeviz/models/shadow_decision_tree.py
  dtreeviz/models/tensorflow_decision_tree.py
  dtreeviz/trees.py
  dtreeviz/utils.py
Labels: clean up

#216 Add matplotlib default colors as mpl_colors
  dtreeviz/colors.py
Labels: enhancement

#218 Fix digraph hard coding
  dtreeviz/trees.py
Labels: clean up

#215 Add option to plot classifier leaves as horizontal bars
  dtreeviz/trees.py
Labels: enhancement

#223 Fix default larrow rarrow
  dtreeviz/colors.py
  dtreeviz/trees.py
Labels: clean up

#224 Fix Digraph Graphics
  dtreeviz/trees.py
Labels: enhancement
