Repository parrt/dtreeviz, pull requests merged in 2023-06, with the labels that each got.

#295 Update README.md; add adapted win10 example for graphviz interface v0…
  README.md
Labels: doc

#297 Fix the left split condition
  dtreeviz/models/sklearn_decision_trees.py
Labels: bug

#296 Make leaves and nodes tmp files paths platform independent
  dtreeviz/trees.py
Labels: cross-platform, clean up

#292 Use prediction from shadow_tree instead of recalculating the mean
  dtreeviz/trees.py
Labels: clean up
